### ISSUE TITLE
functionPriority defined twice in cfgVehicles

### ISSUE THREAD

**Issue by Pergor** [diwako/stalker_anomalies#2]
Hey,

File diwako_anomalies\cfgVehicles.hpp, line 49: /cfgVehicles/anoamly_moduleSpringboard.funktionPriority: Member already defined.

For most of the modules functionPriority is once defined as 1 and again defined as 0.

Hence the mod doesn't work currently.

**Comment by diwako** [comment]
Interesting, looking at the history this has been in since the introduction. Seems these are now the drawbacks for using Addon builder and not mikeros tools. Weirdly enough the modules show up and work ingame. Will investigate.

**Comment by diwako** [comment]
Fixed with latest commit. It should be possible to build with mikero tools now.
